// Auto-generated by fermenta.codegen -- do not edit.
#pragma once
#include <cmath>
#include <cstring>
namespace fermenta {

static inline double omega_wright(double x){
    double y;
    if(x<-3.6){ y=0.929404810843623*std::exp(0.986418416898303*x)-6.79639452545093e-06; }
    else if(x<0.0){ y=-0.00431200176082888*std::exp(3.55275697783407*x)+0.00792228971991872*x*x*x+0.0907827580611564*x*x+0.375633000771424*x+0.571426071298747; }
    else if(x<2.5){ y=-0.531567672565454*std::exp(0.267412600010990*x)-0.00273225759962195*x*x*x+0.0953348873301105*x*x+0.503184890060992*x+1.09876994061414; }
    else if(x<7.0){ y=1.32189881177891*std::exp(-2.05642141379680*x)-0.00164391849625201*x*x*x+0.0428488786259462*x*x+0.481822411934234*x+0.418369998866986; }
    else if(x<30.0){ double b=std::log(x+0.217073722991741); y=1.00007068672705*x-1.00147317311501*b+1.08561409526715*b/x+0.516677184575301*b*(b-2)/(x*x); }
    else { double b=std::log(x); y=x-b+b/x+0.5*b*(b-2)/(x*x); }
    double e=std::exp(x-y), f=y-e, f1=1.0+e;
    return y - f*(1.0-0.5*(f*e/f1)*(f*e/f1))/f1;
}
static inline double diode_scat(double a,double Z,double Is,double eta,double Vth,double Rs,double Rp){
    double al=(2*Rp*Is*Z+a*(Rp+Rs-Z))/(Rp+Rs+Z), be=2*eta*Vth*Z/(Rs+Z);
    double ga=Rp*Is*(Rs+Z)/(eta*Vth*(Rp+Rs+Z)), de=a*(Z-Rs)/(2*eta*Vth*Z);
    return al-be*omega_wright(std::log(ga)+de+al/be);
}
static inline double anti_diode_scat(double a,double Z,double Is,double eta,double Vth,double Rs,double Rp){
    double m=std::fabs(a), s=(a>0)-(a<0);
    double al=(2*Rp*Is*Z+m*(Rp+Rs-Z))/(Rp+Rs+Z), be=2*eta*Vth*Z/(Rs+Z);
    double ga=Rp*Is*(Rs+Z)/(eta*Vth*(Rp+Rs+Z)), de=m*(Z-Rs)/(2*eta*Vth*Z);
    return s*(al-be*omega_wright(std::log(ga)+de+al/be));
}
static inline double diode_res(double v,double i,double Is,double eta,double Vth,double Rs,double Rp){
    double be=eta*Vth, ex=std::exp((v-Rs*i)/be)/be, ri=1.0/Rp;
    return (1.0+Rs*(ri+Is*ex))/(ri+Is*ex);
}
static inline double anti_diode_res(double v,double i,double Is,double eta,double Vth,double Rs,double Rp){
    double be=eta*Vth, hy=2*Is*std::cosh((v-Rs*i)/be)/be, ri=1.0/Rp;
    return (Rs*(hy+ri)+1.0)/(hy+ri);
}
// solve A(n x n) * X = B(n x m), Gaussian elimination w/ partial pivot. A,B destroyed.
template<int NMAX>
static void gsolve(double A[][NMAX], double B[][NMAX], int n, int m){
    for(int c=0;c<n;++c){
        int piv=c; double best=std::fabs(A[c][c]);
        for(int r=c+1;r<n;++r){ double v=std::fabs(A[r][c]); if(v>best){best=v;piv=r;} }
        if(piv!=c){ for(int k=0;k<n;++k){double t=A[c][k];A[c][k]=A[piv][k];A[piv][k]=t;}
                    for(int k=0;k<m;++k){double t=B[c][k];B[c][k]=B[piv][k];B[piv][k]=t;} }
        double d=A[c][c];
        for(int k=0;k<n;++k) A[c][k]/=d;
        for(int k=0;k<m;++k) B[c][k]/=d;
        for(int r=0;r<n;++r){ if(r==c) continue; double f=A[r][c];
            if(f!=0.0){ for(int k=0;k<n;++k) A[r][k]-=f*A[c][k];
                        for(int k=0;k<m;++k) B[r][k]-=f*B[c][k]; } }
    }
    // solution now in B
}

struct MxrDsp {
  static constexpr int N=21, T=11, L=10, NN=21;
  static constexpr int NPOTS=2, NPG=2, NDIODE=1, NDG=1, NOUT=1;
  static constexpr bool SIM=false;
  bool opamp=true;
  double Q[11][N]={{0}};
  double B[10][N]={{0}};
  double Qv[11][N]={{1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.9999999999999982,0.9999999999999991,0.0,-0.9999999999999993,0.0,0.0,0.0},{0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0000000000000004,1.0000000000000004,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0},{0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,1.0,0.0,0.9999999999999999,0.0,0.0,0.0,0.0,0.0,0.0},{0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0000000000000007,0.0,0.0,0.0,0.0,0.0},{0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.9999999999999999,-1.0000000000000007,0.0,1.0000000000000004},{0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0000000000000002,-0.9999999999999987,0.9999999999999998,0.0,-0.9999999999999996,0.0,1.0000000000000002,0.0},{0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,-1.0,0.0,0.0,0.0},{0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0},{0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0},{0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-0.9999999999999984,0.9999999999999992,0.0,-0.9999999999999991,0.0,0.0,0.0},{0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.9999999999999998,0.0,0.0,0.0}};
  double Qi[11][N]={{1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0},{0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0000000000000002,1.0000000000000002,0.0,1.0000000000000002,0.0,0.0,0.0,0.0,0.0,0.0},{0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0000000000000002,1.0000000000000002,0.0,0.9999999999999997,0.0,0.0,0.0,0.0,0.0,0.0},{0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0000000000000002,0.0,0.0,0.0,0.0,0.0},{0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,-1.0000000000000002,0.0,1.0},{0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.9999999999999993,-1.0000000000000004,0.0,0.0,0.0,0.0,0.9999999999999993,0.0},{0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0000000000000004,1.0000000000000002,0.0,0.0,0.0,0.0},{0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0},{0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0000000000000004,0.0,0.0},{0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-0.9999999999999996,0.0,0.0,0.0,0.0,0.0,0.0},{0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.9999999999999996,0.0,0.0,0.0}};
  double Bv[10][N]={{-0.0,1.0000000000000004,1.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0},{-0.0,-1.0000000000000004,-1.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0},{-0.0,-0.0,-0.0,-0.0,-0.0,1.0000000000000002,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0},{0.9999999999999982,-1.0,-0.9999999999999999,-0.0,-0.0,0.9999999999999987,-0.0,-0.0,-0.0,0.9999999999999984,-0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0},{-0.9999999999999991,-0.0,-0.0,-1.0000000000000007,-0.0,-0.9999999999999998,-0.0,-1.0,-0.0,-0.9999999999999992,-0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0},{-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-1.0,-0.0,-0.0,-0.0,-0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0},{0.9999999999999993,-0.0,-0.0,-0.0,-0.9999999999999999,0.9999999999999996,1.0,-0.0,-0.0,0.9999999999999991,0.9999999999999998,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0},{-0.0,-0.0,-0.0,-0.0,1.0000000000000007,-0.0,-0.0,-0.0,1.0,-0.0,-0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0},{-0.0,-0.0,-0.0,-0.0,-0.0,-1.0000000000000002,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0},{-0.0,-0.0,-0.0,-0.0,-1.0000000000000004,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0}};
  double Bi[10][N]={{-0.0,1.0000000000000002,1.0000000000000002,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0},{-0.0,-1.0000000000000002,-1.0000000000000002,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0},{-0.0,-0.0,-0.0,-0.0,-0.0,0.9999999999999993,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0},{1.0,-1.0000000000000002,-0.9999999999999997,-0.0,-0.0,1.0000000000000004,-0.0,-0.0,-0.0,0.9999999999999996,-0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0},{-0.0,-0.0,-0.0,-1.0000000000000002,-0.0,-0.0,1.0000000000000004,-1.0,-0.0,-0.0,-0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0},{-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,-1.0000000000000002,-0.0,-0.0,-0.0,-0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0},{-0.0,-0.0,-0.0,-0.0,-1.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.9999999999999996,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0},{-0.0,-0.0,-0.0,-0.0,1.0000000000000002,-0.0,-0.0,-0.0,1.0000000000000004,-0.0,-0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0},{-0.0,-0.0,-0.0,-0.0,-0.0,-0.9999999999999993,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0},{-0.0,-0.0,-0.0,-0.0,-1.0,-0.0,-0.0,-0.0,-0.0,-0.0,-0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0}};
  int kind[N]={3,1,2,2,5,0,3,2,2,2,3,2,3,3,2,3,2,2,2,2,3};
  double eval[N]={1e-08,9.0,1000000.0,0.0,0.0,0.0,1e-11,4700.0,0.0,10000.0,1e-06,1000000.0,1e-06,1e-09,1000000.0,4.7e-08,1000000.0,10000.0,0.0,1500000.0,1e-09};
  int potIdx[N]={-1,-1,-1,0,-1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1};
  int potRole[N]={0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0};
  int potTypeP[N]={0,0,0,2,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0};
  double potRpP[N]={0.0,0.0,0.0,500000.0,0.0,0.0,0.0,0.0,50000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50000.0,0.0,0.0};
  double potx[NPG]={0.5,0.5};
  static constexpr const char* POTLABEL[NPG] = {"Gain (P1)","Level (P2)"};
  int diodePos[NDG]={4};
  int diodeAnti[NDG]={1};
  double diodeP[NDG][5]={{4.352000000000001e-09,1.905,0.025856300000000002,0.001,1000000.0}};
  int outIdx[NOUT]={8};
  double outSign[NOUT]={-1.0};
  double tolSlv=1e-05, tolDsr=1000.0;
  double fs=48000.0, Z[N], S[N][N], refl[N], inc[N], state[N];
  double av[N], bv[N], vv[N], Rth[NDG];
  MxrDsp(){ reset(); setSampleRate(48000.0); }

    double taper(int type,int role,double x,double Rp){
        const double tol=1e-6;
        if(type==0) return (role==0? x*Rp : (1.0-x)*Rp)+tol;                       // lin
        if(type==1) return (role==0? 0.0125*(std::pow(81.0,x)-1)*Rp                // log
                                   : 1.0125*(1-std::pow(81.0,x-1))*Rp)+tol;
        return (role==0? 0.25*std::log(1+x/0.0125)*Rp/std::log(3.0)               // ilog
                       : 0.25*std::log(1.0125/(x+0.0125))*Rp/std::log(3.0))+tol;
    }
    void buildZ(){
        for(int i=0;i<N;++i){
            switch(kind[i]){
                case 0: Z[i]=1e-9; break;                       // Vin
                case 1: Z[i]=1e-9; break;                       // Vdc
                case 6: Z[i]=1e9;  break;                       // Idc
                case 2: Z[i]= potIdx[i]>=0 ? taper(potTypeP[i],potRole[i],potx[potIdx[i]],potRpP[i]) : eval[i]; break; // R
                case 3: Z[i]=1.0/(2.0*eval[i]*fs); break;       // C
                case 4: Z[i]=2.0*eval[i]*fs; break;             // L
                case 5: /* diode: set by rebuild */ break;
            }
        }
    }
    void buildS(){
        static double M[NN][NN], R[NN][NN];
        if(!opamp){
            for(int r=0;r<L;++r) for(int c=0;c<N;++c){ M[r][c]=B[r][c]; R[r][c]=-B[r][c]; }
            for(int r=0;r<T;++r) for(int c=0;c<N;++c){ double q=Q[r][c]/Z[c]; M[L+r][c]=q; R[L+r][c]=q; }
            gsolve<NN>(M,R,N,N);
            for(int i=0;i<N;++i) for(int j=0;j<N;++j) S[i][j]=R[i][j];
        } else {
            // W = Bv*diag(Z)*Bi^T   (L x L) ;  solve W*Yv = Bv (L x N) ; S = I - 2 diag(Z) Bi^T Yv
            static double W[NN][NN], Yv[NN][NN];
            for(int r=0;r<L;++r) for(int c=0;c<L;++c){ double s=0; for(int k=0;k<N;++k) s+=Bv[r][k]*Z[k]*Bi[c][k]; W[r][c]=s; }
            for(int r=0;r<L;++r) for(int c=0;c<N;++c) Yv[r][c]=Bv[r][c];
            gsolve<NN>(W,Yv,L,N);
            for(int i=0;i<N;++i) for(int j=0;j<N;++j){
                double s=0; for(int k=0;k<L;++k) s+=Bi[k][i]*Yv[k][j];
                S[i][j]=(i==j?1.0:0.0) - 2.0*Z[i]*s;
            }
        }
    }
    void rebuild(){
        buildZ();
        if(NDIODE==1 && !SIM){
            int d=diodePos[0]; Z[d]=1.0; buildS();
            double sdd=S[d][d]; Z[d]=(1.0+sdd)/(1.0-sdd);
            buildS();
        } else if(SIM){
            for(int k=0;k<NDIODE;++k) Z[diodePos[k]]=Rth[k];
            buildS();
        } else {
            buildS();
        }
    }
    void setSampleRate(double f){ fs=f; rebuild(); }
    void setPot(int k,double x){ potx[k]=x; rebuild(); }
    void reset(){
        std::memset(refl,0,sizeof refl); std::memset(inc,0,sizeof inc);
        std::memset(state,0,sizeof state);
        if(SIM){ std::memset(av,0,sizeof av); std::memset(bv,0,sizeof bv);
                 std::memset(vv,0,sizeof vv);
                 for(int k=0;k<NDIODE;++k) Rth[k]=1.0+tolDsr; rebuild(); }
    }
    double process(double in){
        if(!SIM){
            for(int i=0;i<N;++i){
                switch(kind[i]){
                    case 0: refl[i]=in; break;
                    case 1: case 6: refl[i]=eval[i]; break;
                    case 2: refl[i]=0.0; break;
                    case 3: refl[i]=state[i]; break;
                    case 4: refl[i]=-state[i]; break;
                }
            }
            if(NDIODE==1){ int d=diodePos[0]; double aD=0; for(int j=0;j<N;++j) aD+=S[d][j]*refl[j];
                double* p=diodeP[0];
                refl[d]= diodeAnti[0]? anti_diode_scat(aD,Z[d],p[0],p[1],p[2],p[3],p[4])
                                     :      diode_scat(aD,Z[d],p[0],p[1],p[2],p[3],p[4]); }
            for(int i=0;i<N;++i){ double s=0; for(int j=0;j<N;++j) s+=S[i][j]*refl[j]; inc[i]=s; }
            for(int i=0;i<N;++i) if(kind[i]==3||kind[i]==4) state[i]=inc[i];
            double o=0; for(int k=0;k<NOUT;++k) o+=outSign[k]*0.5*(inc[outIdx[k]]+refl[outIdx[k]]);
            return o;
        } else {
            for(int i=0;i<N;++i){
                switch(kind[i]){
                    case 0: bv[i]=in; break;
                    case 1: case 6: bv[i]=eval[i]; break;
                    case 2: bv[i]=0.0; break;
                    case 3: bv[i]=state[i]; break;
                    case 4: bv[i]=-state[i]; break;
                }
            }
            double drift=0; for(int k=0;k<NDIODE;++k) drift+=std::fabs(Z[diodePos[k]]-Rth[k]);
            if(drift>=tolDsr){ for(int k=0;k<NDIODE;++k) Z[diodePos[k]]=Rth[k]; buildS(); }
            double vold[NN]; for(int i=0;i<N;++i) vold[i]=vv[i]+tolSlv;
            int it=0;
            while(it<200){
                double nrm=0; for(int i=0;i<N;++i){ double d=vv[i]-vold[i]; nrm+=d*d; }
                if(std::sqrt(nrm)<tolSlv) break;
                for(int i=0;i<N;++i) vold[i]=vv[i];
                for(int k=0;k<NDIODE;++k){ int d=diodePos[k]; double* p=diodeP[k];
                    bv[d]= diodeAnti[k]? anti_diode_scat(av[d],Z[d],p[0],p[1],p[2],p[3],p[4])
                                       :      diode_scat(av[d],Z[d],p[0],p[1],p[2],p[3],p[4]); }
                for(int i=0;i<N;++i){ double s=0; for(int j=0;j<N;++j) s+=S[i][j]*bv[j]; av[i]=s; }
                for(int i=0;i<N;++i) vv[i]=0.5*(av[i]+bv[i]);
                ++it;
            }
            for(int k=0;k<NDIODE;++k){ int d=diodePos[k]; double* p=diodeP[k];
                double iv=0.5*(av[d]-bv[d])/Z[d];
                Rth[k]= diodeAnti[k]? anti_diode_res(vv[d],iv,p[0],p[1],p[2],p[3],p[4])
                                    :      diode_res(vv[d],iv,p[0],p[1],p[2],p[3],p[4]); }
            for(int i=0;i<N;++i) if(kind[i]==3||kind[i]==4) state[i]=av[i];
            double o=0; for(int k=0;k<NOUT;++k) o+=outSign[k]*0.5*(av[outIdx[k]]+bv[outIdx[k]]);
            return o;
        }
    }

};
} // namespace fermenta