"""
codegen.py -- emit a self-contained, runtime-reconfigurable C++ WDF engine.

Unlike a frozen-matrix export, the emitted DSP stores the topology (Q/B) and the
raw element values, and rebuilds the port resistances Z and scattering matrix S
whenever the sample rate or a potentiometer changes. It also implements the
SIM/DSR iterative solver for multiple nonlinearities. So the generated header
gives:
  * setSampleRate(fs)  -> sample-rate-accurate voicing at any host rate
  * setPot(k, x)       -> live circuit knobs (Gain/Level pots)
  * every circuit class (lin / one_non_lin / *_opamp / non_lin SIM-DSR)

For a single diode, the adapted port resistance Z_D is computed by the same
nullor-MNA reduction VIOLA uses (computeZD() in the emitted header); the constant
part of that system is baked in as znA/znUp/znKp.

Matches fermenta.WDFCircuit -- bit-identical on linear circuits, and within
numerical noise on the ill-conditioned nonlinear ones (tools/validate_cpp.py).
"""
from __future__ import annotations
import numpy as np
from .elements import (IdealVoltageSourcePort, CurrentSourcePort, ResistorPort,
                       CapacitorPort, InductorPort, DiodePort)

# ---- fixed C++ runtime (same for every circuit) ----------------------------
_RUNTIME = r'''// Auto-generated by fermenta.codegen -- do not edit.
#pragma once
#include <cmath>
#include <cstring>
namespace fermenta {

static inline double omega_wright(double x){
    double y;
    if(x<-3.6){ y=0.929404810843623*std::exp(0.986418416898303*x)-6.79639452545093e-06; }
    else if(x<0.0){ y=-0.00431200176082888*std::exp(3.55275697783407*x)+0.00792228971991872*x*x*x+0.0907827580611564*x*x+0.375633000771424*x+0.571426071298747; }
    else if(x<2.5){ y=-0.531567672565454*std::exp(0.267412600010990*x)-0.00273225759962195*x*x*x+0.0953348873301105*x*x+0.503184890060992*x+1.09876994061414; }
    else if(x<7.0){ y=1.32189881177891*std::exp(-2.05642141379680*x)-0.00164391849625201*x*x*x+0.0428488786259462*x*x+0.481822411934234*x+0.418369998866986; }
    else if(x<30.0){ double b=std::log(x+0.217073722991741); y=1.00007068672705*x-1.00147317311501*b+1.08561409526715*b/x+0.516677184575301*b*(b-2)/(x*x); }
    else { double b=std::log(x); y=x-b+b/x+0.5*b*(b-2)/(x*x); }
    double e=std::exp(x-y), f=y-e, f1=1.0+e;
    return y - f*(1.0-0.5*(f*e/f1)*(f*e/f1))/f1;
}
static inline double diode_scat(double a,double Z,double Is,double eta,double Vth,double Rs,double Rp){
    double al=(2*Rp*Is*Z+a*(Rp+Rs-Z))/(Rp+Rs+Z), be=2*eta*Vth*Z/(Rs+Z);
    double ga=Rp*Is*(Rs+Z)/(eta*Vth*(Rp+Rs+Z)), de=a*(Z-Rs)/(2*eta*Vth*Z);
    return al-be*omega_wright(std::log(ga)+de+al/be);
}
static inline double anti_diode_scat(double a,double Z,double Is,double eta,double Vth,double Rs,double Rp){
    double m=std::fabs(a), s=(a>0)-(a<0);
    double al=(2*Rp*Is*Z+m*(Rp+Rs-Z))/(Rp+Rs+Z), be=2*eta*Vth*Z/(Rs+Z);
    double ga=Rp*Is*(Rs+Z)/(eta*Vth*(Rp+Rs+Z)), de=m*(Z-Rs)/(2*eta*Vth*Z);
    return s*(al-be*omega_wright(std::log(ga)+de+al/be));
}
static inline double diode_res(double v,double i,double Is,double eta,double Vth,double Rs,double Rp){
    double be=eta*Vth, ex=std::exp((v-Rs*i)/be)/be, ri=1.0/Rp;
    return (1.0+Rs*(ri+Is*ex))/(ri+Is*ex);
}
static inline double anti_diode_res(double v,double i,double Is,double eta,double Vth,double Rs,double Rp){
    double be=eta*Vth, hy=2*Is*std::cosh((v-Rs*i)/be)/be, ri=1.0/Rp;
    return (Rs*(hy+ri)+1.0)/(hy+ri);
}
// solve A(n x n) * X = B(n x m), Gaussian elimination w/ partial pivot. A,B destroyed.
template<int NMAX>
static void gsolve(double A[][NMAX], double B[][NMAX], int n, int m){
    for(int c=0;c<n;++c){
        int piv=c; double best=std::fabs(A[c][c]);
        for(int r=c+1;r<n;++r){ double v=std::fabs(A[r][c]); if(v>best){best=v;piv=r;} }
        if(piv!=c){ for(int k=0;k<n;++k){double t=A[c][k];A[c][k]=A[piv][k];A[piv][k]=t;}
                    for(int k=0;k<m;++k){double t=B[c][k];B[c][k]=B[piv][k];B[piv][k]=t;} }
        double d=A[c][c];
        for(int k=0;k<n;++k) A[c][k]/=d;
        for(int k=0;k<m;++k) B[c][k]/=d;
        for(int r=0;r<n;++r){ if(r==c) continue; double f=A[r][c];
            if(f!=0.0){ for(int k=0;k<n;++k) A[r][k]-=f*A[c][k];
                        for(int k=0;k<m;++k) B[r][k]-=f*B[c][k]; } }
    }
    // solution now in B
}

// Unblocked LU with partial pivoting (dgetf2-style) + explicit inverse.
template<int NMAX>
static void luinv(double A[][NMAX], double X[][NMAX], int n){
    int piv[NMAX];
    for(int j=0;j<n;++j){
        int p=j; double best=std::fabs(A[j][j]);
        for(int i=j+1;i<n;++i){ double v=std::fabs(A[i][j]); if(v>best){best=v;p=i;} }
        piv[j]=p;
        if(p!=j) for(int k=0;k<n;++k){ double t=A[j][k]; A[j][k]=A[p][k]; A[p][k]=t; }
        double d=A[j][j];
        for(int i=j+1;i<n;++i) A[i][j]/=d;
        for(int i=j+1;i<n;++i){ double l=A[i][j];
            if(l!=0.0) for(int k=j+1;k<n;++k) A[i][k]-=l*A[j][k]; }
    }
    for(int c=0;c<n;++c){
        double x[NMAX];
        for(int i=0;i<n;++i) x[i]=(i==c)?1.0:0.0;
        for(int j=0;j<n;++j){ int p=piv[j]; if(p!=j){ double t=x[j]; x[j]=x[p]; x[p]=t; } }
        for(int i=0;i<n;++i) for(int k=0;k<i;++k) x[i]-=A[i][k]*x[k];
        for(int i=n-1;i>=0;--i){ for(int k=i+1;k<n;++k) x[i]-=A[i][k]*x[k]; x[i]/=A[i][i]; }
        for(int i=0;i<n;++i) X[i][c]=x[i];
    }
}
'''

_METHODS = r'''
    double taper(int type,int role,double x,double Rp){
        const double tol=1e-6;
        if(type==0) return (role==0? x*Rp : (1.0-x)*Rp)+tol;                       // lin
        if(type==1) return (role==0? 0.0125*(std::pow(81.0,x)-1)*Rp                // log
                                   : 1.0125*(1-std::pow(81.0,x-1))*Rp)+tol;
        return (role==0? 0.25*std::log(1+x/0.0125)*Rp/std::log(3.0)               // ilog
                       : 0.25*std::log(1.0125/(x+0.0125))*Rp/std::log(3.0))+tol;
    }
    void buildZ(){
        for(int i=0;i<N;++i){
            switch(kind[i]){
                case 0: Z[i]=1e-9; break;                       // Vin
                case 1: Z[i]=1e-9; break;                       // Vdc
                case 6: Z[i]=1e9;  break;                       // Idc
                case 2: Z[i]= potIdx[i]>=0 ? taper(potTypeP[i],potRole[i],potx[potIdx[i]],potRpP[i]) : eval[i]; break; // R
                case 3: Z[i]=1.0/(2.0*eval[i]*fs); break;       // C
                case 4: Z[i]=2.0*eval[i]*fs; break;             // L
                case 5: /* diode: set by rebuild */ break;
            }
        }
    }
    void buildS(){
        static double M[NN][NN], R[NN][NN];
        if(!opamp){
            for(int r=0;r<L;++r) for(int c=0;c<N;++c){ M[r][c]=B[r][c]; R[r][c]=-B[r][c]; }
            for(int r=0;r<T;++r) for(int c=0;c<N;++c){ double q=Q[r][c]/Z[c]; M[L+r][c]=q; R[L+r][c]=q; }
            gsolve<NN>(M,R,N,N);
            for(int i=0;i<N;++i) for(int j=0;j<N;++j) S[i][j]=R[i][j];
        } else {
            // W = Bv*diag(Z)*Bi^T   (L x L) ;  solve W*Yv = Bv (L x N) ; S = I - 2 diag(Z) Bi^T Yv
            static double W[NN][NN], Yv[NN][NN];
            for(int r=0;r<L;++r) for(int c=0;c<L;++c){ double s=0; for(int k=0;k<N;++k) s+=Bv[r][k]*Z[k]*Bi[c][k]; W[r][c]=s; }
            for(int r=0;r<L;++r) for(int c=0;c<N;++c) Yv[r][c]=Bv[r][c];
            gsolve<NN>(W,Yv,L,N);
            for(int i=0;i<N;++i) for(int j=0;j<N;++j){
                double s=0; for(int k=0;k<L;++k) s+=Bi[k][i]*Yv[k][j];
                S[i][j]=(i==j?1.0:0.0) - 2.0*Z[i]*s;
            }
        }
    }
    // VIOLA's exact Z_n nullor-MNA reduction for the adapted diode port:
    //   Z_n = Yni (I + Up (H - Kp Yni Up)^{-1} Kp Yni), Yni = (Ap Zp^{-1} Ap^T)^{-1}
    // (beta indexed unshifted after the alpha-row removal, as VIOLA does).
    double computeZD(){
        double Yn[ZNM][ZNM]={}, Yni[ZNM][ZNM]={};
        for(int e=0;e<ZNE;++e){ double g=1.0/Z[znPort[e]];
            for(int r=0;r<ZNM;++r){ double ar=znA[r][e]; if(ar==0.0) continue;
                for(int c=0;c<ZNM;++c){ double ac=znA[c][e]; if(ac!=0.0) Yn[r][c]+=g*ar*ac; } } }
        luinv<ZNM>(Yn,Yni,ZNM);   // LU-GEPP (dgetf2-style, same family as LAPACK)
        if(ZOP==0) return Yni[znB][znB];
        double T1[ZNO][ZNM], T2[ZNM][ZNO], M[ZNO][ZNO], Mi[ZNO][ZNO]={};
        for(int i=0;i<ZNO;++i) for(int j=0;j<ZNM;++j){ double t=0; for(int k=0;k<ZNM;++k) t+=znKp[i][k]*Yni[k][j]; T1[i][j]=t; }
        for(int i=0;i<ZNM;++i) for(int j=0;j<ZNO;++j){ double t=0; for(int k=0;k<ZNM;++k) t+=Yni[i][k]*znUp[k][j]; T2[i][j]=t; }
        for(int i=0;i<ZNO;++i) for(int j=0;j<ZNO;++j){ double t=0; for(int k=0;k<ZNM;++k) t+=T1[i][k]*znUp[k][j]; M[i][j]=-t; }  // H=0
        luinv<ZNO>(M,Mi,ZNO);
        double z=Yni[znB][znB];
        for(int i=0;i<ZNO;++i) for(int j=0;j<ZNO;++j) z+=T2[znB][i]*Mi[i][j]*T1[j][znB];
        return z;
    }
    void rebuild(){
        buildZ();
        if(NDIODE==1 && !SIM){
            Z[diodePos[0]]=computeZD();
            buildS();
        } else if(SIM){
            for(int k=0;k<NDIODE;++k) Z[diodePos[k]]=Rth[k];
            buildS();
        } else {
            buildS();
        }
    }
    void setSampleRate(double f){ fs=f; rebuild(); }
    void setPot(int k,double x){ potx[k]=x; rebuild(); }
    void reset(){
        std::memset(refl,0,sizeof refl); std::memset(inc,0,sizeof inc);
        std::memset(state,0,sizeof state);
        if(SIM){ std::memset(av,0,sizeof av); std::memset(bv,0,sizeof bv);
                 std::memset(vv,0,sizeof vv);
                 for(int k=0;k<NDIODE;++k) Rth[k]=1.0+tolDsr; rebuild(); }
    }
    double process(double in){
        if(!SIM){
            for(int i=0;i<N;++i){
                switch(kind[i]){
                    case 0: refl[i]=in; break;
                    case 1: case 6: refl[i]=eval[i]; break;
                    case 2: refl[i]=0.0; break;
                    case 3: refl[i]=state[i]; break;
                    case 4: refl[i]=-state[i]; break;
                }
            }
            if(NDIODE==1){ int d=diodePos[0]; double aD=0; for(int j=0;j<N;++j) aD+=S[d][j]*refl[j];
                double* p=diodeP[0];
                refl[d]= diodeAnti[0]? anti_diode_scat(aD,Z[d],p[0],p[1],p[2],p[3],p[4])
                                     :      diode_scat(aD,Z[d],p[0],p[1],p[2],p[3],p[4]); }
            for(int i=0;i<N;++i){ double s=0; for(int j=0;j<N;++j) s+=S[i][j]*refl[j]; inc[i]=s; }
            for(int i=0;i<N;++i) if(kind[i]==3||kind[i]==4) state[i]=inc[i];
            double o=0; for(int k=0;k<NOUT;++k) o+=outSign[k]*0.5*(inc[outIdx[k]]+refl[outIdx[k]]);
            return o;
        } else {
            for(int i=0;i<N;++i){
                switch(kind[i]){
                    case 0: bv[i]=in; break;
                    case 1: case 6: bv[i]=eval[i]; break;
                    case 2: bv[i]=0.0; break;
                    case 3: bv[i]=state[i]; break;
                    case 4: bv[i]=-state[i]; break;
                }
            }
            double drift=0; for(int k=0;k<NDIODE;++k) drift+=std::fabs(Z[diodePos[k]]-Rth[k]);
            if(drift>=tolDsr){ for(int k=0;k<NDIODE;++k) Z[diodePos[k]]=Rth[k]; buildS(); }
            double vold[NN]; for(int i=0;i<N;++i) vold[i]=vv[i]+tolSlv;
            int it=0;
            while(it<200){
                double nrm=0; for(int i=0;i<N;++i){ double d=vv[i]-vold[i]; nrm+=d*d; }
                if(std::sqrt(nrm)<tolSlv) break;
                for(int i=0;i<N;++i) vold[i]=vv[i];
                for(int k=0;k<NDIODE;++k){ int d=diodePos[k]; double* p=diodeP[k];
                    bv[d]= diodeAnti[k]? anti_diode_scat(av[d],Z[d],p[0],p[1],p[2],p[3],p[4])
                                       :      diode_scat(av[d],Z[d],p[0],p[1],p[2],p[3],p[4]); }
                for(int i=0;i<N;++i){ double s=0; for(int j=0;j<N;++j) s+=S[i][j]*bv[j]; av[i]=s; }
                for(int i=0;i<N;++i) vv[i]=0.5*(av[i]+bv[i]);
                ++it;
            }
            for(int k=0;k<NDIODE;++k){ int d=diodePos[k]; double* p=diodeP[k];
                double iv=0.5*(av[d]-bv[d])/Z[d];
                Rth[k]= diodeAnti[k]? anti_diode_res(vv[d],iv,p[0],p[1],p[2],p[3],p[4])
                                    :      diode_res(vv[d],iv,p[0],p[1],p[2],p[3],p[4]); }
            for(int i=0;i<N;++i) if(kind[i]==3||kind[i]==4) state[i]=av[i];
            double o=0; for(int k=0;k<NOUT;++k) o+=outSign[k]*0.5*(av[outIdx[k]]+bv[outIdx[k]]);
            return o;
        }
    }
'''


def _fmt(x): return repr(float(x))


def _arr2d(A):
    return "{" + ",".join("{" + ",".join(_fmt(v) for v in row) + "}" for row in A) + "}"


def emit_cpp(wdf, name: str, pot_labels=None) -> str:
    N = len(wdf.ports)
    sim = bool(getattr(wdf, "sim", False))
    opamp = bool(wdf.has_opamp)
    inp = wdf.netlist.input_id

    if opamp:
        Q = np.zeros((0, N)); B = np.zeros((0, N))
        QV = wdf._sysd["Q_V"]; QI = wdf._sysd["Q_I"]; BV = wdf._sysd["B_V"]; BI = wdf._sysd["B_I"]
        T, Lc = QV.shape[0], BV.shape[0]
    else:
        Q = np.asarray(wdf.graph.Q); B = np.asarray(wdf.graph.B)
        QV = QI = BV = BI = np.zeros((0, N))
        T, Lc = Q.shape[0], B.shape[0]

    # per-port classification
    kind = [0]*N; eval_ = [0.0]*N
    potIdx = [-1]*N; potRole = [0]*N; potTypeP = [0]*N; potRpP = [0.0]*N
    pot_names = []
    pot_default = []
    port_pot = [None]*N
    _pt = {"Plin": 0, "Plog": 1, "Pilog": 2}
    for i, (p, el) in enumerate(zip(wdf.ports, wdf.elements)):
        if isinstance(p, IdealVoltageSourcePort):
            if el.id == inp: kind[i] = 0
            else: kind[i] = 1; eval_[i] = p.E
        elif isinstance(p, CurrentSourcePort):
            kind[i] = 6; eval_[i] = p.reflect()
        elif isinstance(p, CapacitorPort):
            kind[i] = 3; eval_[i] = float(el.value)
        elif isinstance(p, InductorPort):
            kind[i] = 4; eval_[i] = float(el.value)
        elif isinstance(p, DiodePort):
            kind[i] = 5
        elif isinstance(p, ResistorPort):
            kind[i] = 2
            if el.params and "pot" in el.params:
                nm = el.params["pot"]
                port_pot[i] = nm
                if nm not in pot_names:
                    pot_names.append(nm); pot_default.append(float(el.params.get("x", 0.5)))
                potIdx[i] = pot_names.index(nm)
                potRole[i] = 0 if el.id.endswith("_Ra") else 1
                potTypeP[i] = _pt.get(el.params.get("type", "Plin"), 0)
                potRpP[i] = float(el.params["Rp"])
            else:
                eval_[i] = float(el.value)
        else:
            kind[i] = 2; eval_[i] = float(el.value or 1e12)

    import re as _re
    # Order pots by their natural P-number (P1, P2, ...) so the knob order in the
    # plugin and the potx[] indices match the netlist / potLabels, instead of the
    # internal WDF port order (which can shuffle them).
    def _pnum(nm):
        m = _re.findall(r"\d+", nm)
        return int(m[-1]) if m else (1 << 30)
    _order = sorted(range(len(pot_names)), key=lambda k: (_pnum(pot_names[k]), k))
    pot_names = [pot_names[k] for k in _order]
    pot_default = [pot_default[k] for k in _order]
    for _i in range(N):
        if port_pot[_i] is not None:
            potIdx[_i] = pot_names.index(port_pot[_i])
    NPOTS = len(pot_names)                    # real count (0 if no pots)
    NPG = max(NPOTS, 1)
    if not pot_names:
        pot_default = [0.5]
    else:
        pot_default = list(pot_default)
    while len(pot_default) < NPG:
        pot_default.append(0.5)
    labels = list(pot_labels) if pot_labels else []
    POTLABEL = []
    for _k, _nm in enumerate(pot_names):
        _m = _re.findall(r"\d+", _nm)
        _num = int(_m[-1]) if _m else (_k + 1)
        _lab = labels[_num - 1] if 0 <= _num - 1 < len(labels) else ""
        POTLABEL.append((f"{_lab} (P{_num})" if _lab else f"(P{_num})"))
    while len(POTLABEL) < NPG:
        POTLABEL.append("")

    # diodes
    dpos = list(wdf.diode_idx)
    NDIODE = len(dpos)                      # real count (0/1/>=2)
    danti = [1 if wdf.elements[d].type == "Dap" else 0 for d in dpos]
    dparams = [[wdf.elements[d].params[k] for k in ("Is", "eta", "Vth", "Rs", "Rp")] for d in dpos]
    if NDIODE == 0:                          # pad arrays (C++ has no zero-size arrays)
        dpos = [0]; danti = [0]; dparams = [[1, 1, 1, 1, 1]]
    NDG = max(NDIODE, 1)

    # output path
    if wdf.out_path is not None:
        opath = [(int(j), float(s)) for j, s in wdf.out_path]
    else:
        opath = [(int(wdf.out_idx), 1.0)]
    NOUT = len(opath)

    NN = N  # solver template size

    def ints(v): return "{" + ",".join(str(int(x)) for x in v) + "}"
    def dbls(v): return "{" + ",".join(_fmt(x) for x in v) + "}"

    L = []
    L.append(_RUNTIME)
    L.append(f"struct {name} {{")
    L.append(f"  static constexpr int N={N}, T={T}, L={Lc}, NN={NN};")
    L.append(f"  static constexpr int NPOTS={NPOTS}, NPG={NPG}, NDIODE={NDIODE}, NDG={NDG}, NOUT={NOUT};")
    L.append(f"  static constexpr bool SIM={'true' if sim else 'false'};")
    L.append(f"  bool opamp={'true' if opamp else 'false'};")
    # topology
    L.append(f"  double Q[{max(T,1)}][N]={_arr2d(Q) if not opamp else '{{0}}'};")
    L.append(f"  double B[{max(Lc,1)}][N]={_arr2d(B) if not opamp else '{{0}}'};")
    L.append(f"  double Qv[{max(T,1)}][N]={_arr2d(QV) if opamp else '{{0}}'};")
    L.append(f"  double Qi[{max(T,1)}][N]={_arr2d(QI) if opamp else '{{0}}'};")
    L.append(f"  double Bv[{max(Lc,1)}][N]={_arr2d(BV) if opamp else '{{0}}'};")
    L.append(f"  double Bi[{max(Lc,1)}][N]={_arr2d(BI) if opamp else '{{0}}'};")
    # element specs
    L.append(f"  int kind[N]={ints(kind)};")
    L.append(f"  double eval[N]={dbls(eval_)};")
    L.append(f"  int potIdx[N]={ints(potIdx)};")
    L.append(f"  int potRole[N]={ints(potRole)};")
    L.append(f"  int potTypeP[N]={ints(potTypeP)};")
    L.append(f"  double potRpP[N]={dbls(potRpP)};")
    L.append(f"  double potx[NPG]={dbls(pot_default)};")
    _lbls = "{" + ",".join('"' + x.replace('"', '\\"') + '"' for x in POTLABEL) + "}"
    L.append(f"  static constexpr const char* POTLABEL[NPG] = {_lbls};")
    # VIOLA Z_n MNA data (single-diode closed-form only)
    if NDIODE == 1 and not sim:
        Ared, eport, Up, Kp, zb, znO = wdf._viola_mna_data(dpos[0])
        znm, zne = Ared.shape
        zno = max(znO, 1)
        L.append(f"  static constexpr int ZNM={znm}, ZNE={zne}, ZNO={zno}, ZOP={znO}, znB={zb};")
        L.append(f"  double znA[ZNM][ZNE]={_arr2d(Ared)};")
        L.append(f"  int znPort[ZNE]={ints(eport)};")
        _up = Up if znO else [[0.0]] * znm
        _kp = Kp if znO else [[0.0] * znm]
        L.append(f"  double znUp[ZNM][ZNO]={_arr2d(_up)};")
        L.append(f"  double znKp[ZNO][ZNM]={_arr2d(_kp)};")
    else:
        L.append("  static constexpr int ZNM=1, ZNE=1, ZNO=1, ZOP=0, znB=0;")
        L.append("  double znA[ZNM][ZNE]={{0.0}};")
        L.append("  int znPort[ZNE]={0};")
        L.append("  double znUp[ZNM][ZNO]={{0.0}};")
        L.append("  double znKp[ZNO][ZNM]={{0.0}};")
    # diode
    L.append(f"  int diodePos[NDG]={ints(dpos)};")
    L.append(f"  int diodeAnti[NDG]={ints(danti)};")
    L.append(f"  double diodeP[NDG][5]={_arr2d(dparams)};")
    # output + tolerances
    L.append(f"  int outIdx[NOUT]={ints([j for j,_ in opath])};")
    L.append(f"  double outSign[NOUT]={dbls([s for _,s in opath])};")
    L.append(f"  double tolSlv={_fmt(wdf.tol_slv)}, tolDsr={_fmt(wdf.tol_dsr)};")
    # runtime state
    L.append("  double fs=48000.0, Z[N], S[N][N], refl[N], inc[N], state[N];")
    L.append("  double av[N], bv[N], vv[N], Rth[NDG];")
    L.append(f"  {name}(){{ reset(); setSampleRate(48000.0); }}")
    L.append(_METHODS)
    L.append("};")
    L.append("} // namespace fermenta")
    return "\n".join(L)
